services:
    oracle: #from https://geraldonit.com/2021/08/15/oracle-xe-docker-images/ and https://oralytics.com/2021/10/01/oracle-21c-xe-database-and-docker-setup/
      image: gvenzl/oracle-xe:latest
      container_name: oracle21c
      ports:
      - "15210:1521"
      environment:
      - ORACLE_PASSWORD=Welcome1
      volumes:
      - ./init_scripts:/container-entrypoint-initdb.d
    iris:
      build: 
        context: .
        dockerfile: Dockerfile
      restart: always
      command: --check-caps false
      ports: 
        - 19721:1972
        - 52773:52773
        - 53773:53773
      volumes:
        - ./:/irisrun/repo