    // Unexpire passwords to simplify dev mode. Comment these two lines for Production use
    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")

    // create IRISAPP namespace
    do $SYSTEM.OBJ.Load("/opt/irisbuild/Installer.cls", "ck")
    set sc = ##class(App.Installer).setup() 
    zn "USER"
    do $SYSTEM.OBJ.Load("/opt/irisbuild/src/dc/test/TestClass.cls", "ck") 

    halt
